namespace DemoApi.Models
{
    /// <summary>
    /// Response returned to the external system
    /// </summary>
    public class ExternalTransactionResponse
    {
        /// <summary>
        /// Operation status
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Identifier generated by the external system
        /// </summary>
        public int ExternalId { get; set; }

        /// <summary>
        /// Optional informational message
        /// </summary>
        public string Message { get; set; }
    }
}
